<template>
  <div class="wrapper">
    <video
      class="video"
      :class="facingMode === 'user' ? 'front' : ''"
      ref="video"
    />
    <canvas style="display: none" ref="canva" />

    <button
      v-if="videoDevices.length > 1"
      class="button is-rounded is-outlined switch-button"
      @click="switchCamera"
      :disabled="switchingCamera"
    >
      <b-icon pack="fas" icon="sync-alt" />
    </button>
    <div class="photo-button-container">
      <button class="button photo-button" @mousedown="startTimer" @mouseup="stopTimer">
        <b-icon pack="fas" icon="camera" />
      </button>
    </div>
    <photos-gallery class="gallery" :photos="photos" />
  </div>
</template>

<script>
import PhotosGallery from "./PhotosGallery.vue";
export default {
  components: {
    PhotosGallery,
  },
  data() {
    return {
      photos: [],
      mediaStream: null,
      videoDevices: [],
      facingMode: "environment",
      counter: 0,
      switchingCamera: false,
      interval: null,
      timer: 0,
    };
  },
  methods: {
    /**
     * Creates an anchor element with the file data within the page and clicks
     * it to open up a download prompt.
    */
    downloadImage(filename, imageData){
      let file = document.createElement('a');

      file.setAttribute('href', imageData);
      file.setAttribute('download', filename);

      document.body.appendChild(file);
      file.click();
      document.body.removeChild(file);
    },

    /**
     * When run starts an interval that increments a value once every 10ms
    */
    async startTimer(){
      this.interval = setInterval(() => {
        this.timer++;
      }, 10);
    },

    /**
     * If the timer start in the startTimer method has a value greater than
     * "minimumTimeForLongPress", then the last value generated by the 
     * TakePhoto method will be passed to the downloadImage method.
    */
    stopTimer(){
      let minimumTimeForLongPress = 100;
      clearInterval(this.interval);

      this.TakePhoto();
      
      if(this.timer > minimumTimeForLongPress){
        let photo = this.photos[this.photos.length - 1];

        this.downloadImage(photo.id + '.png', photo.src);
      }

      this.timer = 0;
    },
    async StartRecording(facingMode) {
      this.facingMode = facingMode;
      let video = this.$refs.video;
      this.mediaStream = await navigator.mediaDevices.getUserMedia({
        video: { facingMode: facingMode },
      });
      video.srcObject = this.mediaStream;
      return await video.play();
    },
    async TakePhoto() {
      let video = this.$refs.video;
      let canva = this.$refs.canva;
      let width = video.videoWidth;
      let height = video.videoHeight;
      canva.width = width;
      canva.height = height;
      let ctx = canva.getContext("2d");
      ctx.save();

      if (this.facingMode === "user") {
        ctx.scale(-1, 1);
        ctx.drawImage(video, width * -1, 0, width, height);
      } else {
        ctx.drawImage(video, 0, 0);
      }

      ctx.restore();

      this.photos.push({
        id: this.counter++,
        src: canva.toDataURL("image/png"),
      });
    },
    async switchCamera() {
      this.switchingCamera = true;
      const tracks = this.mediaStream.getVideoTracks();
      tracks.forEach((track) => {
        track.stop();
      });
      await this.StartRecording(
        this.facingMode === "environment" ? "user" : "environment"
      );
      this.switchingCamera = false;
    },
  },
  async mounted() {
    const devices = await navigator.mediaDevices.enumerateDevices();
    this.videoDevices = devices.filter((d) => d.kind === "videoinput");
    await this.StartRecording(
      this.videoDevices.length === 1 ? "user" : "environment"
    );
  },
};
</script>

<style scoped>
.video.front {
  -webkit-transform: scaleX(-1);
  transform: scaleX(-1);
}
.wrapper {
  background-color: black;
  display: grid;
  width: 100vw;
  height: 100vh;
  grid-template-columns: [left] 90vw [bs] 5vw [es] 5vw [right];
  grid-template-rows: [top] 5vh [bs] 5vh [es] 60vh [middle] 10vh [bottom] 20vh [end];
  justify-items: center;
  overflow: hidden;
}

.video {
  height: 100%;
  grid-column: left/right;
  grid-row: top / bottom;
  user-select: none;
  max-width: unset;
}

.switch-button {
  grid-column: bs / es;
  grid-row: bs / es;
  z-index: 5;
  border-radius: 100%;
  width: 6vh;
  height: 6vh;
  font-size: 2vh;
}

.photo-button-container {
  grid-column: left / right;
  grid-row: middle / bottom;
  z-index: 5;
  width: 100vw;
  height: 20vh;
  display: flex;
  justify-content: center;
}

.photo-button {
  width: 10vh;
  height: 10vh;
  border-radius: 100%;
}

.photo-button {
  font-size: 4vh;
  color: black;
}
.gallery {
  grid-column: left / right;
  grid-row: bottom / end;
}
</style>
