<template>
  <img :src="src" @mousedown="startTimer" @mouseup="stopTimer" />
</template>

<script>
export default {
  props: {
    src: {
      type: String,
      default: null,
    },
  },

  data(){
    return {
      interval: null,
      timer: 0,
    }
  },

  methods: {
    /**
     * Creates an anchor element with the file data within the page and clicks
     * it to open up a download prompt.
    */
    downloadImage(){
      let file = document.createElement('a');
      let filename = Math.random().toString(36).substring(7) + '.png';

      file.setAttribute('href', this.src);
      file.setAttribute('download', filename);
      document.body.appendChild(file);
      file.click();
      document.body.removeChild(file);
    },

    /**
     * When run starts an interval that increments a value once every 10ms
    */
    async startTimer(){
      this.interval = setInterval(() => {
        this.timer++;
      }, 10);
    },

    /**
     * If the timer start in the startTimer method has a value greater than
     * "minimumTimeForLongPress", then the last value generated by the 
     * TakePhoto method will be passed to the downloadImage method.
    */
    stopTimer(){
      let minimumTimeForLongPress = 100;
      clearInterval(this.interval);
      
      if(this.timer > minimumTimeForLongPress){
        this.showDownloadPrompt();
      }
      this.timer = 0;
    },

    async showDownloadPrompt(){
      this.$buefy.dialog.confirm({
        title: 'Download image',
        message: '<img src="' + this.src + '" />',
        confirmText: 'Yes',
        type: 'is-success',
        onConfirm: () => this.downloadImage()
      });
    }
  }
};
</script>

<style scoped>
img {
  height: 100%;
}
</style>